# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=16, unique=True)),
                ('firebase_device_id', models.CharField(blank=True, max_length=2048, null=True)),
                ('encrypted_password', models.CharField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
